version: '3.9'

services:
    django:
        build: ./app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8090:8000
        # environmental variables
        environment:
            # 1 is debug mode
            - DEBUG=1
            # - SECRET_KEY='django-insecure-!)+bp)dx6c0c-+jhq)%z(#yjw$zmjs6y+5dc!0v+06o2o3bz(x'
