# Generated by Django 3.2.4 on 2021-06-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'service',
                'ordering': ('name',),
            },
        ),
    ]
