# Generated by Django 3.2.5 on 2021-07-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OsintList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osint_id', models.CharField(max_length=100, unique=True)),
                ('osint_type', models.IntegerField(choices=[(0, 'INVALID'), (1, 'IPADDRESS'), (2, 'DOMAIN'), (3, 'FILEHASH')], null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('malicious_level', models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'MALICIOUS'), (2, 'SUSPICIOUS'), (3, 'SAFE')], null=True)),
            ],
            options={
                'verbose_name': 'OSINT',
                'verbose_name_plural': 'OSINT List',
                'ordering': ('osint_id',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'service',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VtSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100, null=True)),
                ('gui_url', models.URLField(null=True, unique=True)),
                ('malicious_level', models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'MALICIOUS'), (2, 'SUSPICIOUS'), (3, 'SAFE')], null=True)),
                ('malicious_possibility', models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'MALICIOUS'), (2, 'SUSPICIOUS'), (3, 'SAFE')], null=True)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
                ('osint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osiete_osint.osintlist')),
            ],
            options={
                'verbose_name': 'OSINT',
                'verbose_name_plural': 'VirusTotal Summary',
                'ordering': ('osint_id',),
            },
        ),
        migrations.CreateModel(
            name='VtComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('osint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osiete_osint.osintlist')),
            ],
            options={
                'verbose_name': 'OSINT',
                'verbose_name_plural': 'VirusTotal Comments',
                'ordering': ('osint_id',),
            },
        ),
        migrations.CreateModel(
            name='UrlScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('primary_ip', models.CharField(max_length=50, null=True)),
                ('server', models.CharField(max_length=50, null=True)),
                ('asnname', models.CharField(max_length=50, null=True)),
                ('asn', models.CharField(max_length=50, null=True)),
                ('ptr', models.CharField(max_length=100, null=True)),
                ('screenshot', models.URLField(null=True)),
                ('osint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osiete_osint.osintlist')),
            ],
            options={
                'verbose_name': 'OSINT',
                'verbose_name_plural': 'urlscan.io information',
                'ordering': ('osint_id',),
            },
        ),
        migrations.CreateModel(
            name='OsintSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('from_ip', models.CharField(max_length=16, verbose_name='from ipaddr')),
                ('osint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osiete_osint.osintlist')),
            ],
            options={
                'verbose_name': 'OSINT',
                'verbose_name_plural': 'OSINT Search History',
                'ordering': ('osint_id',),
            },
        ),
    ]
