# Generated by Django 3.2.4 on 2021-06-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osiete_osint', '0003_auto_20210626_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osintlist',
            old_name='last_analyzed',
            new_name='updated_at',
        ),
    ]
