# Generated by Django 3.2.4 on 2021-07-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osiete_osint', '0004_rename_last_analyzed_osintlist_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlscan',
            name='asn',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='asnname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='primary_ip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='server',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
